#
# file: .travis.yml
#
# author: Copyright (C) 2015-2017 Kamil Szczygiel http://www.distortec.com http://www.freddiechopin.info
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# use container-based infrastructure
sudo: false

# texinfo is needed to build bleeding-edge-toolchain
addons:
    apt:
        packages:
            - texinfo
            - texlive

cache:
    directories:
        - "${HOME}/cache"

# use minimal environment
language: generic

matrix:
    include:
        - env: SUBSTAGE="build 5"
        - env: SUBSTAGE="build 6"
        - python: '2.7'
          env: SUBSTAGE="pydts --quiet"
        - python: '3.6'
          env: SUBSTAGE="pydts --quiet"

before_install:
    - "export PATH=${HOME}/.local/bin:${PATH}"

install:
    - "XZ_OPT=\"-0 -T 0 -v\" ./scripts/travis-ci.sh install ${SUBSTAGE}"

script:
    - "./scripts/travis-ci.sh script ${SUBSTAGE}"

after_failure:
    - "echo \"********** /tmp/stdout.log\""
    - "tail -n 1000 /tmp/stdout.log"
    - "echo \"********** /tmp/stderr.log\""
    - "tail -n 1000 /tmp/stderr.log"
