#
# file: .travis.yml
#
# author: Copyright (C) 2015-2016 Kamil Szczygiel http://www.distortec.com http://www.freddiechopin.info
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# use container-based infrastructure
sudo: false

# texinfo is needed to build bleeding-edge-toolchain
addons:
    apt:
        packages:
            - texinfo

# use minimal environment
language: generic

install:
    - "./scripts/travis-ci.sh install"

script:
    - "./scripts/travis-ci.sh script"
