#
# file: .travis.yml
#
# author: Copyright (C) 2015-2018 Kamil Szczygiel http://www.distortec.com http://www.freddiechopin.info
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

# use "trusty", container-based infrastructure
dist: trusty
sudo: false

addons:
    apt:
        packages:
            - ninja-build

# use Python environment for generateBoard stage
language: python

matrix:
    include:
        - env: SUBSTAGE="build 5"
        - env: SUBSTAGE="build 6"
        - env: SUBSTAGE="build 7"
        - env: SUBSTAGE="build 8"
        - python: '2.7'
          env: SUBSTAGE="generateBoard"
        - python: '3.6'
          env: SUBSTAGE="generateBoard"
        - env: SUBSTAGE="unit-test" COMPILER_NAME=gcc CC=gcc-7 CXX=g++-7
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-7
                      - g++-7
                      - ninja-build

install:
    - "./scripts/travis-ci.sh install ${SUBSTAGE}"

script:
    - "./scripts/travis-ci.sh script ${SUBSTAGE}"

after_failure:
    - "echo \"********** ls -la ${TRAVIS_BUILD_DIR}/output\""
    - "ls -la ${TRAVIS_BUILD_DIR}/output"
    - "echo \"********** cat ${TRAVIS_BUILD_DIR}/output/*.preprocessed.ld\""
    - "cat ${TRAVIS_BUILD_DIR}/output/*.preprocessed.ld"
    - "echo \"********** cat output/include/distortos/distortosConfiguration.h\""
    - "cat output/include/distortos/distortosConfiguration.h"
