#
# file: test-board-generator.yml
#
# author: Copyright (C) 2021-2022 Kamil Szczygiel https://distortec.com https://freddiechopin.info
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
# distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
#

name: Test Board Generator

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test-board-generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install jinja2 ruamel.yaml
    - name: Generate Boards
      shell: bash
      run: |
        for yamlFile in $(/usr/bin/find -L "${GITHUB_WORKSPACE}/source/board" -name '*.yaml')
        do
          ${GITHUB_WORKSPACE}/scripts/generateBoard.py ${yamlFile}
        done

        git add -N .
        git diff --exit-code
    - name: Generate "Raw" Boards
      shell: bash
      run: |
        for yamlFile in $(/usr/bin/find -L "${GITHUB_WORKSPACE}/source/chip" -name '*.yaml')
        do
          ${GITHUB_WORKSPACE}/scripts/generateBoard.py ${yamlFile} -o /tmp/$(basename ${yamlFile} .yaml)
        done
